---
- hosts: amazonweb
  become: yes
  #become_user: root or any other user
  tasks:
    - name: "download java 1.8"
      yum: name=java-1.8.0 state=installed     

    - name: "download a file from internet"
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.0/bin/apache-tomcat-8.5.0.tar.gz
        dest: /opt                                                                    # download file on remote server

    - name: "unarchive the tomcat 8.5 tar file"
      unarchive:
        src: /opt/apache-tomcat-8.5.0.tar.gz                                          # file location. file is available on remote server
        dest: /opt                                                                    # untar the file at this location
        remote_src: yes                                                               # if file is present on remote server  


    - name: "copy webapp.war file from ansible master to remote server"
      copy:
        src: /etc/ansible/playbooks/webapp/target/webapp.war
        dest: /opt/apache-tomcat-8.5.0/webapps

    - name: "restart tomcat process to reflect the changes"
      command: nohup /opt/apache-tomcat-8.5.0/bin/shutdown.sh

    - name: "start tomcat service by calling /opt/apache-tomcat-8.5.0/bin/startup.sh" 
      command: nohup /opt/apache-tomcat-8.5.0/bin/startup.sh                                         # to run startup.sh file
  
  
