apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:         #should match with line 14
      app: nginx
      date: 7-4-21
  replicas: 2 
  template:
    metadata:
      labels:
        app: nginx       #should match with line 31
        date: 7-4-21
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
  labels:
    svc: myservice
spec:
  selector:
    app: nginx
    date: 7-4-21
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
  type:
    NodePort
